modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId = "sullysmod" #mandatory
version = "${file.jarVersion}" #mandatory
logoFile = "sullysmod_banner.png" #optional
authors = "Uraneptus" #optional
credits = "Idea & Assets by Sully" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/sullys-mobs"
displayName = "Sully's Mod" #mandatory
description = '''
'''

[[dependencies.sullysmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.sullysmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sullysmod]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.0.0,)"
    ordering = "BEFORE"
    side = "BOTH"
