modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Uraneptus/Sullys-Mod/issues"

[[mods]] #mandatory
modId = "sullysmod" #mandatory
version = "${file.jarVersion}" #mandatory
logoFile = "sullysmod_banner.png" #optional
authors = "Uraneptus, MiteBeMana" #optional
credits = "Idea & Assets by Sully" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/sullys-mod"
displayName = "Sully's Mod" #mandatory
description = '''
'''

[[dependencies.sullysmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.sullysmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sullysmod]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.3.1,)"
    ordering = "BEFORE"
    side = "BOTH"

[[dependencies.sullysmod]]
    modId = "geckolib3"
    mandatory = true
    versionRange = "[3.0.18,)"
    ordering = "BEFORE"
    side = "BOTH"
